START TRANSACTION;

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);


CREATE TABLE cariche (
    carica_id integer GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(100) NOT NULL,
    descrizione text,
    ordine integer NOT NULL,
    CONSTRAINT "PK_cariche" PRIMARY KEY (carica_id)
);

CREATE TABLE eventi (
    evento_id integer GENERATED BY DEFAULT AS IDENTITY,
    titolo character varying(200) NOT NULL,
    descrizione text,
    data_inizio timestamp with time zone NOT NULL,
    data_fine timestamp with time zone,
    luogo character varying(200),
    tipo_evento character varying(50) NOT NULL,
    stato character varying(20) NOT NULL,
    budget numeric(10,2),
    spese_effettive numeric(10,2),
    incassi numeric(10,2),
    note text,
    immagine_url text,
    pubblicato boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_eventi" PRIMARY KEY (evento_id)
);

CREATE TABLE impostazioni (
    chiave character varying(100) NOT NULL,
    valore text,
    descrizione character varying(200),
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_impostazioni" PRIMARY KEY (chiave)
);

CREATE TABLE riunioni (
    riunione_id integer GENERATED BY DEFAULT AS IDENTITY,
    data_riunione timestamp with time zone NOT NULL,
    ora_inizio interval NOT NULL,
    ora_fine interval,
    luogo character varying(255),
    tipo_riunione character varying(100) NOT NULL,
    note text,
    verbale text,
    numero_verbale character varying(50),
    stato_verbale character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_riunioni" PRIMARY KEY (riunione_id)
);

CREATE TABLE soci (
    socio_id integer GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(100) NOT NULL,
    cognome character varying(100) NOT NULL,
    codice_fiscale character varying(16) NOT NULL,
    data_nascita timestamp with time zone NOT NULL,
    indirizzo character varying(200),
    telefono character varying(20),
    email character varying(100),
    data_iscrizione timestamp with time zone NOT NULL,
    carica_id integer,
    stato_socio character varying(20) NOT NULL,
    data_cessazione timestamp with time zone,
    note text,
    foto_url text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_soci" PRIMARY KEY (socio_id),
    CONSTRAINT "FK_soci_cariche_carica_id" FOREIGN KEY (carica_id) REFERENCES cariche (carica_id)
);

CREATE TABLE argomenti_riunione (
    argomento_id integer GENERATED BY DEFAULT AS IDENTITY,
    riunione_id integer NOT NULL,
    titolo character varying(255) NOT NULL,
    descrizione text,
    ordine integer NOT NULL,
    CONSTRAINT "PK_argomenti_riunione" PRIMARY KEY (argomento_id),
    CONSTRAINT "FK_argomenti_riunione_riunioni_riunione_id" FOREIGN KEY (riunione_id) REFERENCES riunioni (riunione_id) ON DELETE CASCADE
);

CREATE TABLE documenti (
    documento_id integer GENERATED BY DEFAULT AS IDENTITY,
    socio_id integer NOT NULL,
    tipo_documento character varying(50) NOT NULL,
    nome_file character varying(200) NOT NULL,
    path_file text NOT NULL,
    data_caricamento timestamp with time zone NOT NULL,
    data_scadenza timestamp with time zone,
    CONSTRAINT "PK_documenti" PRIMARY KEY (documento_id),
    CONSTRAINT "FK_documenti_soci_socio_id" FOREIGN KEY (socio_id) REFERENCES soci (socio_id) ON DELETE CASCADE
);

CREATE TABLE partecipazioni_eventi (
    partecipazione_evento_id integer GENERATED BY DEFAULT AS IDENTITY,
    evento_id integer NOT NULL,
    socio_id integer NOT NULL,
    ruolo character varying(50),
    note text,
    data_iscrizione timestamp with time zone NOT NULL,
    confermato boolean NOT NULL,
    CONSTRAINT "PK_partecipazioni_eventi" PRIMARY KEY (partecipazione_evento_id),
    CONSTRAINT "FK_partecipazioni_eventi_eventi_evento_id" FOREIGN KEY (evento_id) REFERENCES eventi (evento_id) ON DELETE CASCADE,
    CONSTRAINT "FK_partecipazioni_eventi_soci_socio_id" FOREIGN KEY (socio_id) REFERENCES soci (socio_id) ON DELETE CASCADE
);

CREATE TABLE partecipazioni_riunioni (
    partecipazione_id integer GENERATED BY DEFAULT AS IDENTITY,
    riunione_id integer NOT NULL,
    socio_id integer NOT NULL,
    presente boolean NOT NULL,
    ruolo character varying(100),
    CONSTRAINT "PK_partecipazioni_riunioni" PRIMARY KEY (partecipazione_id),
    CONSTRAINT "FK_partecipazioni_riunioni_riunioni_riunione_id" FOREIGN KEY (riunione_id) REFERENCES riunioni (riunione_id) ON DELETE CASCADE,
    CONSTRAINT "FK_partecipazioni_riunioni_soci_socio_id" FOREIGN KEY (socio_id) REFERENCES soci (socio_id) ON DELETE CASCADE
);

CREATE TABLE soci_cariche (
    socio_carica_id integer GENERATED BY DEFAULT AS IDENTITY,
    socio_id integer NOT NULL,
    carica_id integer NOT NULL,
    data_inizio timestamp with time zone NOT NULL,
    data_fine timestamp with time zone,
    note text,
    CONSTRAINT "PK_soci_cariche" PRIMARY KEY (socio_carica_id),
    CONSTRAINT "FK_soci_cariche_cariche_carica_id" FOREIGN KEY (carica_id) REFERENCES cariche (carica_id) ON DELETE CASCADE,
    CONSTRAINT "FK_soci_cariche_soci_socio_id" FOREIGN KEY (socio_id) REFERENCES soci (socio_id) ON DELETE CASCADE
);

CREATE TABLE users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY,
    username character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    password_hash text NOT NULL,
    nome character varying(100),
    cognome character varying(100),
    socio_id integer,
    ruolo character varying(20) NOT NULL,
    attivo boolean NOT NULL,
    ultimo_accesso timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY (user_id),
    CONSTRAINT "FK_users_soci_socio_id" FOREIGN KEY (socio_id) REFERENCES soci (socio_id) ON DELETE SET NULL
);

CREATE TABLE delibere_riunioni (
    delibera_id integer GENERATED BY DEFAULT AS IDENTITY,
    riunione_id integer NOT NULL,
    argomento_id integer,
    numero_delibera character varying(50) NOT NULL,
    oggetto character varying(500) NOT NULL,
    testo text,
    esito character varying(50),
    voti_favorevoli integer,
    voti_contrari integer,
    voti_astenuti integer,
    CONSTRAINT "PK_delibere_riunioni" PRIMARY KEY (delibera_id),
    CONSTRAINT "FK_delibere_riunioni_argomenti_riunione_argomento_id" FOREIGN KEY (argomento_id) REFERENCES argomenti_riunione (argomento_id) ON DELETE SET NULL,
    CONSTRAINT "FK_delibere_riunioni_riunioni_riunione_id" FOREIGN KEY (riunione_id) REFERENCES riunioni (riunione_id) ON DELETE CASCADE
);

CREATE TABLE notifiche (
    notifica_id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    tipo_notifica character varying(50) NOT NULL,
    titolo character varying(200) NOT NULL,
    messaggio text NOT NULL,
    link text,
    letta boolean NOT NULL,
    data_lettura timestamp with time zone,
    data_invio timestamp with time zone NOT NULL,
    data_scadenza timestamp with time zone,
    riferimento_id integer,
    riferimento_tipo character varying(50),
    CONSTRAINT "PK_notifiche" PRIMARY KEY (notifica_id),
    CONSTRAINT "FK_notifiche_users_user_id" FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

INSERT INTO cariche (carica_id, descrizione, nome, ordine)
VALUES (1, 'Presidente dell''associazione', 'Presidente', 1);
INSERT INTO cariche (carica_id, descrizione, nome, ordine)
VALUES (2, 'Vice Presidente dell''associazione', 'Vice Presidente', 2);
INSERT INTO cariche (carica_id, descrizione, nome, ordine)
VALUES (3, 'Segretario dell''associazione', 'Segretario', 3);
INSERT INTO cariche (carica_id, descrizione, nome, ordine)
VALUES (4, 'Tesoriere dell''associazione', 'Tesoriere', 4);
INSERT INTO cariche (carica_id, descrizione, nome, ordine)
VALUES (5, 'Membro del consiglio', 'Consigliere', 5);
INSERT INTO cariche (carica_id, descrizione, nome, ordine)
VALUES (6, 'Socio fondatore', 'Socio Fondatore', 6);
INSERT INTO cariche (carica_id, descrizione, nome, ordine)
VALUES (7, 'Revisore dei conti', 'Revisore dei Conti', 7);

CREATE INDEX "IX_argomenti_riunione_riunione_id" ON argomenti_riunione (riunione_id);

CREATE INDEX "IX_delibere_riunioni_argomento_id" ON delibere_riunioni (argomento_id);

CREATE INDEX "IX_delibere_riunioni_riunione_id" ON delibere_riunioni (riunione_id);

CREATE INDEX "IX_documenti_socio_id" ON documenti (socio_id);

CREATE UNIQUE INDEX "IX_impostazioni_chiave" ON impostazioni (chiave);

CREATE INDEX "IX_notifiche_user_id" ON notifiche (user_id);

CREATE INDEX "IX_partecipazioni_eventi_evento_id" ON partecipazioni_eventi (evento_id);

CREATE INDEX "IX_partecipazioni_eventi_socio_id" ON partecipazioni_eventi (socio_id);

CREATE INDEX "IX_partecipazioni_riunioni_riunione_id" ON partecipazioni_riunioni (riunione_id);

CREATE INDEX "IX_partecipazioni_riunioni_socio_id" ON partecipazioni_riunioni (socio_id);

CREATE INDEX "IX_soci_carica_id" ON soci (carica_id);

CREATE UNIQUE INDEX "IX_soci_codice_fiscale" ON soci (codice_fiscale);

CREATE INDEX "IX_soci_cariche_carica_id" ON soci_cariche (carica_id);

CREATE INDEX "IX_soci_cariche_socio_id" ON soci_cariche (socio_id);

CREATE UNIQUE INDEX "IX_users_email" ON users (email);

CREATE INDEX "IX_users_socio_id" ON users (socio_id);

CREATE UNIQUE INDEX "IX_users_username" ON users (username);

SELECT setval(
    pg_get_serial_sequence('cariche', 'carica_id'),
    GREATEST(
        (SELECT MAX(carica_id) FROM cariche) + 1,
        nextval(pg_get_serial_sequence('cariche', 'carica_id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251229152507_InitialCreate', '8.0.0');

COMMIT;

