// <auto-generated />
using System;
using AssociazioneETS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssociazioneETS.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260107110141_AddPushSubscriptions")]
    partial class AddPushSubscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssociazioneETS.API.Models.ArgomentoRiunione", b =>
                {
                    b.Property<int>("ArgomentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("argomento_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArgomentoId"));

                    b.Property<string>("Descrizione")
                        .HasColumnType("text")
                        .HasColumnName("descrizione");

                    b.Property<int>("Ordine")
                        .HasColumnType("integer")
                        .HasColumnName("ordine");

                    b.Property<int>("RiunioneId")
                        .HasColumnType("integer")
                        .HasColumnName("riunione_id");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("titolo");

                    b.HasKey("ArgomentoId");

                    b.HasIndex("RiunioneId");

                    b.ToTable("argomenti_riunione");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.Carica", b =>
                {
                    b.Property<int>("CaricaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("carica_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CaricaId"));

                    b.Property<string>("Descrizione")
                        .HasColumnType("text")
                        .HasColumnName("descrizione");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordine")
                        .HasColumnType("integer")
                        .HasColumnName("ordine");

                    b.HasKey("CaricaId");

                    b.ToTable("cariche");

                    b.HasData(
                        new
                        {
                            CaricaId = 1,
                            Descrizione = "Presidente dell'associazione",
                            Nome = "Presidente",
                            Ordine = 1
                        },
                        new
                        {
                            CaricaId = 2,
                            Descrizione = "Vice Presidente dell'associazione",
                            Nome = "Vice Presidente",
                            Ordine = 2
                        },
                        new
                        {
                            CaricaId = 3,
                            Descrizione = "Segretario dell'associazione",
                            Nome = "Segretario",
                            Ordine = 3
                        },
                        new
                        {
                            CaricaId = 4,
                            Descrizione = "Tesoriere dell'associazione",
                            Nome = "Tesoriere",
                            Ordine = 4
                        },
                        new
                        {
                            CaricaId = 5,
                            Descrizione = "Membro del consiglio",
                            Nome = "Consigliere",
                            Ordine = 5
                        },
                        new
                        {
                            CaricaId = 6,
                            Descrizione = "Socio fondatore",
                            Nome = "Socio Fondatore",
                            Ordine = 6
                        },
                        new
                        {
                            CaricaId = 7,
                            Descrizione = "Revisore dei conti",
                            Nome = "Revisore dei Conti",
                            Ordine = 7
                        });
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.DeliberaRiunione", b =>
                {
                    b.Property<int>("DeliberaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("delibera_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliberaId"));

                    b.Property<int?>("ArgomentoId")
                        .HasColumnType("integer")
                        .HasColumnName("argomento_id");

                    b.Property<string>("Esito")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("esito");

                    b.Property<string>("NumeroDelibera")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_delibera");

                    b.Property<string>("Oggetto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("oggetto");

                    b.Property<int>("RiunioneId")
                        .HasColumnType("integer")
                        .HasColumnName("riunione_id");

                    b.Property<string>("Testo")
                        .HasColumnType("text")
                        .HasColumnName("testo");

                    b.Property<int?>("VotiAstenuti")
                        .HasColumnType("integer")
                        .HasColumnName("voti_astenuti");

                    b.Property<int?>("VotiContrari")
                        .HasColumnType("integer")
                        .HasColumnName("voti_contrari");

                    b.Property<int?>("VotiFavorevoli")
                        .HasColumnType("integer")
                        .HasColumnName("voti_favorevoli");

                    b.HasKey("DeliberaId");

                    b.HasIndex("ArgomentoId");

                    b.HasIndex("RiunioneId");

                    b.ToTable("delibere_riunioni");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.Documento", b =>
                {
                    b.Property<int>("DocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("documento_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentoId"));

                    b.Property<DateTime>("DataCaricamento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_caricamento");

                    b.Property<DateTime?>("DataScadenza")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_scadenza");

                    b.Property<string>("NomeFile")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_file");

                    b.Property<string>("PathFile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path_file");

                    b.Property<int>("SocioId")
                        .HasColumnType("integer")
                        .HasColumnName("socio_id");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("DocumentoId");

                    b.HasIndex("SocioId");

                    b.ToTable("documenti");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("evento_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventoId"));

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("budget");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DataFine")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_fine");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_inizio");

                    b.Property<string>("Descrizione")
                        .HasColumnType("text")
                        .HasColumnName("descrizione");

                    b.Property<string>("ImmagineUrl")
                        .HasColumnType("text")
                        .HasColumnName("immagine_url");

                    b.Property<decimal?>("Incassi")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("incassi");

                    b.Property<string>("Luogo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("luogo");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<bool>("Pubblicato")
                        .HasColumnType("boolean")
                        .HasColumnName("pubblicato");

                    b.Property<decimal?>("SpeseEffettive")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("spese_effettive");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stato");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_evento");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titolo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EventoId");

                    b.ToTable("eventi");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.Impostazione", b =>
                {
                    b.Property<string>("Chiave")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chiave");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descrizione");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Valore")
                        .HasColumnType("text")
                        .HasColumnName("valore");

                    b.HasKey("Chiave");

                    b.HasIndex("Chiave")
                        .IsUnique();

                    b.ToTable("impostazioni");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.Notifica", b =>
                {
                    b.Property<int>("NotificaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notifica_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificaId"));

                    b.Property<DateTime>("DataInvio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_invio");

                    b.Property<DateTime?>("DataLettura")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_lettura");

                    b.Property<DateTime?>("DataScadenza")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_scadenza");

                    b.Property<bool>("Letta")
                        .HasColumnType("boolean")
                        .HasColumnName("letta");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<string>("Messaggio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("messaggio");

                    b.Property<int?>("RiferimentoId")
                        .HasColumnType("integer")
                        .HasColumnName("riferimento_id");

                    b.Property<string>("RiferimentoTipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("riferimento_tipo");

                    b.Property<string>("TipoNotifica")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_notifica");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titolo");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("NotificaId");

                    b.HasIndex("UserId");

                    b.ToTable("notifiche");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.PartecipazioneEvento", b =>
                {
                    b.Property<int>("PartecipazioneEventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("partecipazione_evento_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartecipazioneEventoId"));

                    b.Property<bool>("Confermato")
                        .HasColumnType("boolean")
                        .HasColumnName("confermato");

                    b.Property<DateTime>("DataIscrizione")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_iscrizione");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer")
                        .HasColumnName("evento_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Ruolo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ruolo");

                    b.Property<int>("SocioId")
                        .HasColumnType("integer")
                        .HasColumnName("socio_id");

                    b.HasKey("PartecipazioneEventoId");

                    b.HasIndex("EventoId");

                    b.HasIndex("SocioId");

                    b.ToTable("partecipazioni_eventi");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.PartecipazioneRiunione", b =>
                {
                    b.Property<int>("PartecipazioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("partecipazione_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartecipazioneId"));

                    b.Property<bool>("Presente")
                        .HasColumnType("boolean")
                        .HasColumnName("presente");

                    b.Property<int>("RiunioneId")
                        .HasColumnType("integer")
                        .HasColumnName("riunione_id");

                    b.Property<string>("Ruolo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ruolo");

                    b.Property<int>("SocioId")
                        .HasColumnType("integer")
                        .HasColumnName("socio_id");

                    b.HasKey("PartecipazioneId");

                    b.HasIndex("RiunioneId");

                    b.HasIndex("SocioId");

                    b.ToTable("partecipazioni_riunioni");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.Riunione", b =>
                {
                    b.Property<int>("RiunioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("riunione_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RiunioneId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataRiunione")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_riunione");

                    b.Property<string>("Luogo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("luogo");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("NumeroVerbale")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_verbale");

                    b.Property<TimeSpan?>("OraFine")
                        .HasColumnType("interval")
                        .HasColumnName("ora_fine");

                    b.Property<TimeSpan>("OraInizio")
                        .HasColumnType("interval")
                        .HasColumnName("ora_inizio");

                    b.Property<string>("StatoVerbale")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stato_verbale");

                    b.Property<string>("TipoRiunione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_riunione");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Verbale")
                        .HasColumnType("text")
                        .HasColumnName("verbale");

                    b.HasKey("RiunioneId");

                    b.ToTable("riunioni");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.Socio", b =>
                {
                    b.Property<int>("SocioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("socio_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SocioId"));

                    b.Property<int?>("CaricaId")
                        .HasColumnType("integer")
                        .HasColumnName("carica_id");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("codice_fiscale");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cognome");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DataCessazione")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cessazione");

                    b.Property<DateTime>("DataIscrizione")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_iscrizione");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_nascita");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("foto_url");

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("indirizzo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("StatoSocio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stato_socio");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SocioId");

                    b.HasIndex("CaricaId");

                    b.HasIndex("CodiceFiscale")
                        .IsUnique();

                    b.ToTable("soci");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.SocioCarica", b =>
                {
                    b.Property<int>("SocioCaricaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("socio_carica_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SocioCaricaId"));

                    b.Property<int>("CaricaId")
                        .HasColumnType("integer")
                        .HasColumnName("carica_id");

                    b.Property<DateTime?>("DataFine")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_fine");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_inizio");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("SocioId")
                        .HasColumnType("integer")
                        .HasColumnName("socio_id");

                    b.HasKey("SocioCaricaId");

                    b.HasIndex("CaricaId");

                    b.HasIndex("SocioId");

                    b.ToTable("soci_cariche");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("boolean")
                        .HasColumnName("attivo");

                    b.Property<string>("Cognome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cognome");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ruolo");

                    b.Property<int?>("SocioId")
                        .HasColumnType("integer")
                        .HasColumnName("socio_id");

                    b.Property<DateTime?>("UltimoAccesso")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ultimo_accesso");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SocioId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.ArgomentoRiunione", b =>
                {
                    b.HasOne("AssociazioneETS.API.Models.Riunione", "Riunione")
                        .WithMany("Argomenti")
                        .HasForeignKey("RiunioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Riunione");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.DeliberaRiunione", b =>
                {
                    b.HasOne("AssociazioneETS.API.Models.ArgomentoRiunione", "Argomento")
                        .WithMany("Delibere")
                        .HasForeignKey("ArgomentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssociazioneETS.API.Models.Riunione", "Riunione")
                        .WithMany("Delibere")
                        .HasForeignKey("RiunioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Argomento");

                    b.Navigation("Riunione");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.Documento", b =>
                {
                    b.HasOne("AssociazioneETS.API.Models.Socio", "Socio")
                        .WithMany("Documenti")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.Notifica", b =>
                {
                    b.HasOne("AssociazioneETS.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.PartecipazioneEvento", b =>
                {
                    b.HasOne("AssociazioneETS.API.Models.Evento", "Evento")
                        .WithMany("Partecipazioni")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssociazioneETS.API.Models.Socio", "Socio")
                        .WithMany("PartecipazioniEventi")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.PartecipazioneRiunione", b =>
                {
                    b.HasOne("AssociazioneETS.API.Models.Riunione", "Riunione")
                        .WithMany("Partecipazioni")
                        .HasForeignKey("RiunioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssociazioneETS.API.Models.Socio", "Socio")
                        .WithMany("PartecipazioniRiunioni")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Riunione");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.Socio", b =>
                {
                    b.HasOne("AssociazioneETS.API.Models.Carica", "Carica")
                        .WithMany("Soci")
                        .HasForeignKey("CaricaId");

                    b.Navigation("Carica");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.SocioCarica", b =>
                {
                    b.HasOne("AssociazioneETS.API.Models.Carica", "Carica")
                        .WithMany("SociCariche")
                        .HasForeignKey("CaricaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssociazioneETS.API.Models.Socio", "Socio")
                        .WithMany("SociCariche")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carica");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.User", b =>
                {
                    b.HasOne("AssociazioneETS.API.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.ArgomentoRiunione", b =>
                {
                    b.Navigation("Delibere");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.Carica", b =>
                {
                    b.Navigation("Soci");

                    b.Navigation("SociCariche");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.Evento", b =>
                {
                    b.Navigation("Partecipazioni");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.Riunione", b =>
                {
                    b.Navigation("Argomenti");

                    b.Navigation("Delibere");

                    b.Navigation("Partecipazioni");
                });

            modelBuilder.Entity("AssociazioneETS.API.Models.Socio", b =>
                {
                    b.Navigation("Documenti");

                    b.Navigation("PartecipazioniEventi");

                    b.Navigation("PartecipazioniRiunioni");

                    b.Navigation("SociCariche");
                });
#pragma warning restore 612, 618
        }
    }
}
